name: Validate Formatting

on:
  pull_request:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check sort titles
        run: grep -o '## .*' README.md | sort -c